#!/bin/sh

PSEUDO_DIR='../Pseudo/'
TMP_DIR='./tmp'
BIN_DIR='/usr/local/apps/espresso-5.1/bin/'

PARA_PREFIX='mpirun -np 2'
PARA_POSTFIX=' -nk 1 -nd 1 -nb 1 -nt 1 '


# create temporary directory 
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"

for DIR in "$TMP_DIR" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO 'Si bulk: scf nrun, gamma-point '

    # self-consistent calculation
cat > si_nscf.in << EOF
&control
 calculation='nscf'
 restart_mode='from_scratch',
 prefix='si'
 pseudo_dir = '$PSEUDO_DIR/',
 outdir='$TMP_DIR/'
/
&system
 ibrav= 8, celldm(1)= 10.26,celldm(2)= 1, celldm(3)=1,
 nat=  8, ntyp= 1,
 ecutwfc = 15.0,nbnd=32
/
&electrons
 diagonalization='david',
 conv_thr =  1.0d-10,
 mixing_beta = 0.5,
 startingwfc='random',
/
ATOMIC_SPECIES
Si  1. Si.pz-vbc.UPF
ATOMIC_POSITIONS (crystal)
Si 0.00000 0.00000 0.00000
Si 0.50000 0.50000 0.00000
Si 0.00000 0.50000 0.50000
Si 0.50000 0.00000 0.50000
Si 0.25000 0.25000 0.25000
Si 0.75000 0.75000 0.25000
Si 0.75000 0.25000 0.75000
Si 0.25000 0.75000 0.75000

EOF
    $ECHO "  running the nscf calculation for Si...\c"
    $PW_COMMAND < si_nscf.in > si_nscf.out
