#!/bin/sh

PSEUDO_DIR='../Pseudo/'
TMP_DIR='./tmp'
BIN_DIR='/usr/local/apps/espresso-5.1/bin/'

PARA_PREFIX='mpirun -np 2'


# create temporary directory 
HEAD_COMMAND="$PARA_PREFIX $BIN_DIR/head.x "

for DIR in "$TMP_DIR"; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO 'Si bulk: head run'

    # self-consistent calculation
cat > si_head.in << EOF
calculation of head
 &inputph
  trans=.false.
  l_head=.true.
  tr2_ph=1.d-4,
  prefix='si',
  omega_gauss=20.0
  n_gauss=97
  grid_type=5
  second_grid_i=1
  second_grid_n=10
  niter_ph=1
  nsteps_lanczos=30
  outdir='$TMP_DIR/'
 /
0.0 0.0 0.0

EOF

$ECHO "  running the head calculation for Si bulk...\c"
$HEAD_COMMAND < si_head.in > si_head.out
$ECHO " done"

cp tmp/_ph0/*head tmp/
