#!/bin/sh

PSEUDO_DIR='../Pseudo/'
TMP_DIR='./tmp'
BIN_DIR='/usr/local/apps/espresso-5.1/bin/'

PARA_PREFIX='mpirun -np 2'


# create temporary directory 
GWW_COMMAND="$PARA_PREFIX $BIN_DIR/gww.x "

for DIR in "$TMP_DIR"; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO 'Si bulk: gww run'

    # self-consistent calculation
cat > si_gww.in << EOF
&inputgww
ggwin%prefix='si'
ggwin%n=97,
ggwin%n_fit=120,
ggwin%max_i=32,
ggwin%i_min=1
ggwin%i_max=32
ggwin%l_truncated_coulomb=.false.
ggwin%grid_time=3
ggwin%grid_freq=5
ggwin%second_grid_i=1
ggwin%second_grid_n=10
ggwin%omega=20
ggwin%omega_fit=20
ggwin%n_grid_fit=240
ggwin%tau=9.8
ggwin%n_set_pola=16
ggwin%outdir='$TMP_DIR'
/


EOF
    $ECHO "  running the gww calculation for Si...\c"
    $GWW_COMMAND < si_gww.in > si_gww.out
    $ECHO " done"
