#!/bin/sh

PSEUDO_DIR='../Pseudo/'
TMP_DIR='./tmp'
BIN_DIR='/usr/local/apps/espresso-5.1/bin/'

PARA_PREFIX='mpirun -np 2'


# create temporary directory 
PW4_COMMAND="$PARA_PREFIX $BIN_DIR/pw4gww.x "

for DIR in "$TMP_DIR"; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO 'Si bulk: pw4gww run'

    # self-consistent calculation
cat > si_pw4gww.in << EOF
&inputpw4gww    
    prefix='si'
    num_nbndv(1)=16
    num_nbnds=32
    l_truncated_coulomb=.false.
    numw_prod=100
    pmat_cutoff=3d0
    s_self_lanczos=1d-8
    outdir='$TMP_DIR'
/


EOF
    $ECHO "  running the pw4gww calculation for Si...\c"
    $PW4_COMMAND < si_pw4gww.in > si_pw4gww.out
    $ECHO " done"
