#!/bin/sh
####################################################################
# set the needed environment variables
. ../environment_variables
####################################################################
# define some QE variables (do not change)
pseudo=gpbe-n-campos.uspp
name=Fe
struct=bcc.FM
lattice_const=2.85
nK=20
degauss=0.005


mkdir results.band

cd results.band



# scf calculation
cat >  $name.$struct.scf.in << EOF
 &control
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    prefix='$name.$struct'
 /
 &system
    ibrav = 3, a =$lattice_const, nat= 1, ntyp= 1,
    nspin = 2,   
    ecutwfc = 35, ecutrho = 350.0,
    starting_magnetization(1)=0.3,
    occupations='smearing', smearing='MV', degauss=$degauss
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.7   
 /
ATOMIC_SPECIES
$name 55.847 $name.$pseudo.UPF
ATOMIC_POSITIONS {alat}
 $name 0.0 0.0 0.0
K_POINTS automatic
 $nK $nK $nK 0 0 0
EOF
$PW_ROOT/pw.x < $name.$struct.scf.in > $name.$struct.scf.out

# band calculation
cat > $name.$struct.band.in << EOF
 &control
    calculation='bands'     
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    prefix='$name.$struct'
    verbosity='high'
 /
 &system
    ibrav = 3, a =$lattice_const, nat= 1, ntyp= 1, nbnd=7,
    nspin = 2,      
    ecutwfc = 35, ecutrho = 350.0,
    occupations='smearing', smearing='MV', degauss=$degauss
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.3   
 /
ATOMIC_SPECIES
 $name 55.847  $name.$pseudo.UPF
ATOMIC_POSITIONS {alat}
 $name 0.0 0.0 0.0
K_POINTS (tpiba_b)
6
0.0 0.0 0.0  20
0.5 0.5 0.0  20
0.5 0.5 0.5  20
0.0 0.0 0.0  20
0.0 1.0 0.0  20
0.5 0.5 0.0  1
EOF

$PW_ROOT/pw.x < $name.$struct.band.in > $name.$struct.band.out

cat >  $name.$struct.bands.in << EOF
 &bands
    outdir='$TMP_DIR/'
    prefix='$name.$struct'
    filband='$name.$struct.bands.up'
    spin_component= 1
    lsym=.true.
 /
EOF
$PW_ROOT/bands.x < $name.$struct.bands.in > $name.$struct.bands.up.out

sed '1d' $name.$struct.bands.up  >$name.$struct.bands.up.tempo 
cat >tempo <<EOF
7 101
EOF

cat tempo $name.$struct.bands.up.tempo >$name.$struct.bands.up
\rm -f -r $name.$struct.bands.up.tempo
\rm -f tempo
cat >  $name.$struct.bands.in << EOF
 &bands
    outdir='$TMP_DIR/'
    prefix='$name.$struct'
    filband='$name.$struct.bands.dn'
    spin_component= 2
    lsym=.true.    
 /
EOF
$PW_ROOT/bands.x < $name.$struct.bands.in > $name.$struct.bands.dn.out

sed '1d' $name.$struct.bands.dn >$name.$struct.bands.dn.tempo 
cat >tempo <<EOF
7 101
EOF

cat tempo $name.$struct.bands.dn.tempo >$name.$struct.bands.dn
\rm -f -r $name.$struct.bands.dn.tempo
\rm -f tempo

../../make_bands.x<$name.$struct.bands.up>$name.$struct.bands.up.dat
../../make_bands.x<$name.$struct.bands.dn>$name.$struct.bands.dn.dat


