#!/bin/sh

PSEUDO_DIR='../Pseudo/'
TMP_DIR='./tmp'
BIN_DIR='/usr/local/apps/espresso-5.1/bin/'

PARA_PREFIX='mpirun -np 2'
PARA_POSTFIX=' -nk 1 -nd 1 -nb 1 -nt 1 '


# create temporary directory 
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"

for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO 'Co: scf run, gamma point'

    # self-consistent calculation
cat > CO_scf.in << EOF
&control
    calculation = 'scf',
    restart_mode='from_scratch',
    prefix='CO',
    tprnfor = .true.,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav=  1,
    celldm(1) =10.0,
    nat=2,
    ntyp= 2,
    ecutwfc =40.0,
    nbnd=6
 /
 &electrons
    diagonalization='cg'
    mixing_beta = 0.5,
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
O  1.00  O.pw-mt_fhi.UPF
C  1.00  C.pw-mt_fhi.UPF
ATOMIC_POSITIONS {bohr}
C        2.162706264   0.000000000   0.000000000
O        0.000000000   0.000000000   0.000000000    0   0   0
EOF
$ECHO "  running the scf calculation for CO...\c"
$PW_COMMAND < CO_scf.in > CO_scf.out
$ECHO " done"
