#!/bin/bash
#PBS -q lionxi-seminar
#PBS -l nodes=1:ppn=4
#PBS -l walltime=1:00:00
#PBS -j oe
####################################################################
#
#

export PW_COMMAND=/usr/local/apps/espresso-5.1/bin/pw.x
export PP_COMMAND=/usr/local/apps/espresso-5.1/bin/projwfc.x
export PSEUDO_DIR=../pseudo
#export workdir=~/advanced-xc_DFTPU/FeO

export results=./results_FeO_NO_U

#cd $workdir

if [ ! -d $results ]; then
   mkdir  $results
fi

if [ ! -d temp ]; then
   mkdir  temp
fi

# self-consistent calculation
cat > feo.scf.in << EOF
 &control
    pseudo_dir = '$PSEUDO_DIR',
    outdir='temp'
    prefix='feo',
 /
 &system
    ibrav=0, 
    celldm(1)=8.19, 
    nat=4, 
    ntyp= 3,
    ecutwfc = 30.0, ecutrho = 240.0,
    occupations='smearing', 
    smearing='mp', 
    degauss=0.02,
    nspin=2, 
    starting_magnetization(2)= 0.5, 
    starting_magnetization(3)=-0.5,
    lda_plus_u = .true.,
    Hubbard_U(1) = 1.d-10,
    Hubbard_U(2) = 1.d-10,
    Hubbard_U(3) = 1.d-10,
 /
 &electrons
    mixing_beta = 0.3 
 /
CELL_PARAMETERS
0.50 0.50 1.00
0.50 1.00 0.50
1.00 0.50 0.50
ATOMIC_SPECIES
 O    1.  O.pbe-rrkjus.UPF
 Fe1  1.  Fe.pbe-nd-rrkjus.UPF
 Fe2  1.  Fe.pbe-nd-rrkjus.UPF
ATOMIC_POSITIONS crystal
 O  0.25 0.25 0.25
 O  0.75 0.75 0.75
 Fe1 0.0  0.0  0.0 
 Fe2 0.5  0.5  0.5
K_POINTS automatic
4 4 4 0 0 0
EOF

mpirun -np 4 $PW_COMMAND < feo.scf.in  > $results/feo.scf.out

# non self-consistent calculation
cat > feo.nscf.in << EOF
 &control
    calculation='nscf'
    pseudo_dir = '$PSEUDO_DIR',
    outdir='temp'
    prefix='feo',
 /
 &system
    ibrav=0, 
    celldm(1)=8.19, 
    nat=  4, 
    ntyp= 3,
    ecutwfc = 30.0, 
    ecutrho = 240.0,
    nbnd=24,
    occupations='smearing', 
    smearing='mp', 
    degauss=0.02,
    nspin=2, 
    starting_magnetization(2)= 0.5, 
    starting_magnetization(3)=-0.5,
    lda_plus_u = .true.,
    Hubbard_U(2) = 1.d-10,
    Hubbard_U(3) = 1.d-10,
 /
 &electrons
    mixing_beta = 0.3 
 /
CELL_PARAMETERS
0.50 0.50 1.00
0.50 1.00 0.50
1.00 0.50 0.50
ATOMIC_SPECIES
 O    1.  O.pbe-rrkjus.UPF
 Fe1  1.  Fe.pbe-nd-rrkjus.UPF
 Fe2  1.  Fe.pbe-nd-rrkjus.UPF
ATOMIC_POSITIONS crystal
 O  0.25 0.25 0.25
 O  0.75 0.75 0.75
 Fe1 0.0  0.0  0.0 
 Fe2 0.5  0.5  0.5
K_POINTS automatic
8 8 8 0 0 0
EOF
mpirun  -np 4 $PW_COMMAND < feo.nscf.in  > $results/feo.nscf.out

cat > feo.pdos.in << EOF
 &projwfc
    outdir='temp'
    prefix='feo'
    DeltaE=0.1
 /
EOF

mpirun -np 4 $PP_COMMAND < feo.pdos.in  > $results/feo.pdos.out

mv feo.*out feo.pdos*atm*wfc $results/
