#!/bin/sh

PSEUDO_DIR='../Pseudo/'
TMP_DIR='./tmp'
BIN_DIR='/usr/local/apps/espresso-5.1/bin/'

PARA_PREFIX='mpirun -np 2'
PARA_POSTFIX=' -nk 1 -nd 1 -nb 1 -nt 1 '


# create temporary directory 
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"

for DIR in "$TMP_DIR" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO 'Methane: scf run, gamma point'

    # self-consistent calculation
cat > methane_scf.in << EOF
&control
    calculation = 'scf',
    restart_mode='from_scratch',
    prefix='ch4',
    tprnfor = .true.,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav=  1,
    celldm(1) =15.0,
    nat=5,
    ntyp= 2,
    ecutwfc =40.0,
    nbnd=5
 /
 &electrons
    diagonalization='cg'
    mixing_beta = 0.5,
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 H  1.0   H.pz-vbc.UPF
 C  12.0  C.pz-vbc.UPF
ATOMIC_POSITIONS {bohr}
H        1.198204546   1.198204546   1.198204546
H       -1.198204546  -1.198204546   1.198204546
H        1.198204546  -1.198204546  -1.198204546
H       -1.198204546   1.198204546  -1.198204546
C        0.000000000   0.000000000   0.000000000

EOF
$ECHO "  running the scf calculation for methane...\c"
$PW_COMMAND < methane_scf.in > methane_scf.out
$ECHO " done"
