#!/bin/sh

PSEUDO_DIR='../Pseudo/'
TMP_DIR='./tmp'
BIN_DIR='/usr/local/apps/espresso-5.1/bin/'

PARA_PREFIX='mpirun -np 2'
PARA_POSTFIX=' -nk 1 -nd 1 -nb 1 -nt 1 '

PW4GWW_COMMAND="$PARA_PREFIX $BIN_DIR/pw4gww.x $PARA_POSTFIX"

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

cat > methane_pw4gww.in << EOF
&inputpw4gww    
    prefix='ch4'
    num_nbndv(1)=4
    num_nbnds=5
    l_truncated_coulomb=.true.
    truncation_radius=7.5d0
    numw_prod=50
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
/

EOF
$ECHO "  running the pw4gww calculation for methane...\c"
$PW4GWW_COMMAND < methane_pw4gww.in > methane_pw4gww.out
$ECHO " done"

